feat : Add Fabric8 Maven Plugin deprecation log message before & after goal executions
fabric8io/fabric8-maven-plugin pull request #1833
Opened 2022-06-02 13:48 UTC by rohanKanojia

# Description

Related to https://github.com/eclipse/jkube/issues/1426

Add warning log message to print deprecation message and instruct users
to migrate to Eclipse JKube

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

2022-06-09 13:26 UTC, manusa commented on core/src/main/java/io/fabric8/maven/core/util/Fabric8MavenPluginDeprecationUtil.java
> +      logger.warn("Fabric8 Maven Plugin has been deprecated and would no longer be supported in future.\n\n" +
```suggestion
      logger.warn("Fabric8 Maven Plugin has been deprecated and is no longer be supported.\n\n" +
```

2022-06-09 13:26 UTC, manusa commented on core/src/main/java/io/fabric8/maven/core/util/Fabric8MavenPluginDeprecationUtil.java
> +          "You can read Migration Guide for more details (https://www.eclipse.org/jkube/docs/migration-guide/)\n\n" +
```suggestion
          "You can read the Migration Guide for more details (https://www.eclipse.org/jkube/docs/migration-guide/)\n\n" +
```

2022-06-09 13:27 UTC, manusa commented on doc/src/main/asciidoc/inc/_introduction.adoc
> +IMPORTANT: *Fabric8 Maven Plugin has been deprecated and would no longer be supported in future.
is no longer supported

2022-06-09 13:28 UTC, manusa commented
@sunix could you please take a look

2022-06-10 13:59 UTC, sunix commented
> @sunix could you please take a look
I cannot add myself as a reviewer

2022-06-10 14:06 UTC, manusa commented
> do we want to do this now or in a next release/pr? [eclipse/jkube#287 (comment)](https://github.com/eclipse/jkube/issues/287#issuecomment-1144581566)
> 
> > Maybe what we can do is in the next release:
> > 
> > * fail when excuting one of the goals.
> > * display warnings about the problems with using fmp and provide different resolution options
> > * have a flag for user who still wants to use fmp that would reenable the goals.

That would be a period (3-6 months) after we release these changes

2022-06-10 14:06 UTC, manusa commented
> > @sunix could you please take a look
> 
> I cannot add myself as a reviewer

:smile: yes, that's why I pinged you in a message. But you should be able to provide a review or comment an LGTM

2022-06-13 09:17 UTC, sunix requested changes
Naming of the test method looks wrong.
Otherwise looks good to me.

2022-06-13 09:17 UTC, sunix commented on core/src/test/java/io/fabric8/maven/core/util/Fabric8MavenPluginDeprecationUtilTest.java
> +  public void logFabric8MavenPluginDeprecation_whenLogDeprecationFalse_shouldLogDeprecationWarning() {
`..._shouldLogDeprecationWarning` or `..._shouldNotLogDeprecationWarning` ?

2022-06-13 09:50 UTC, manusa commented on doc/src/main/asciidoc/inc/_introduction.adoc
> +IMPORTANT: *Fabric8 Maven Plugin is deprecated and is no longer be supported.
```suggestion
IMPORTANT: *Fabric8 Maven Plugin is deprecated and is no longer supported.
```

2022-06-13 10:07 UTC, manusa approved these changes

2022-06-13 10:08 UTC, merged